#!/usr/bin/env ansible-playbook
---
- hosts: tycoch
  sudo: yes
  gather_facts: yes
  tasks:

    - name: Update and upgrade apt packages
      apt:
        upgrade: safe
        update_cache: yes
        cache_valid_time: 3600

    - name: install update-ansible
      copy:
        src: files/usr/local/bin/update-ansible
        dest: /usr/local/bin/
        owner: root
        group: staff
        mode: 0755

    - name: install setup-readonly.sh
      copy:
        src: files/usr/local/bin/setup-readonly.sh
        dest: /usr/local/bin/
        owner: root
        group: staff
        mode: 0755

    - name: install set-ro
      copy:
        src: files/usr/local/bin/set-ro
        dest: /usr/local/bin/
        owner: root
        group: staff
        mode: 0755

    - name: install set-rw
      copy:
        src: files/usr/local/bin/set-rw
        dest: /usr/local/bin/
        owner: root
        group: staff
        mode: 0755

    - name: enable uart in /boot/config.txt
      lineinfile: dest=/boot/config.txt state=present line="enable_uart=1"

    - name: install setup-influx.sh
      copy:
        src: files/usr/local/bin/setup-influx.sh
        dest: /usr/local/bin/
        owner: root
        group: staff
        mode: 0755

    - name: Create /data directory
      file:
        path: /data
        state: directory

    - name: Create /data-ramdisk directory
      file:
        path: /data-ramdisk
        state: directory

    - name: add /data-ramdisk to fstab
      lineinfile: dest=/etc/fstab state=present line="tmpfs       /data-ramdisk tmpfs   nodev,nosuid,noexec,nodiratime,size=128M   0 0"

    - name: add /data to fstab
      lineinfile: dest=/etc/fstab state=present line="/dev/mmcblk0p3  /data           ext4    defaults,noatime  0       0"

    - name: install udev rules for USB serial
      copy:
        src: files/etc/udev/rules.d/99-usb-serial.rules
        dest: /etc/udev/rules.d/99-usb-serial.rules
        owner: root
        group: root
        mode: 0644

    - name: Enable I2C
      command: "raspi-config nonint do_i2c 0"
      args:
        creates: /sys/class/i2c-adapter/i2c-1

    - name: add ds1307 to /boot/config.txt
      lineinfile: dest=/boot/config.txt state=present line="dtoverlay=i2c-rtc,ds1307"

    - name: Remove fake-hwclock
      apt:
        name: fake-hwclock
        state: absent

    - name: Patch hwclock-set
      patch:
        src: files/hwclock.patch
        dest: /lib/udev/hwclock-set

    - name: Install git
      apt:
        name: git
        update_cache: yes
        cache_valid_time: 3600

    - name: Install vim
      apt:
        name: vim
        update_cache: yes
        cache_valid_time: 3600

    - name: Install tmux
      apt:
        name: tmux
        update_cache: yes
        cache_valid_time: 3600

    - name: Install pip
      apt:
        name: python-pip
        update_cache: yes
        cache_valid_time: 3600

    - name: Install i2c-tools
      apt:
        name: i2c-tools
        update_cache: yes
        cache_valid_time: 3600

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
        cache_valid_time: 3600

    - name: Install the tycoch software
      git:
        repo: 'https://github.com/bjpirt/tycoch-software.git'
        dest: /usr/local/tycoch/software
        update: yes

    - name: Install pymodbus
      pip:
        name: pymodbus

    - name: Install paho-mqtt
      pip:
        name: paho-mqtt

    - name: Install requests
      pip:
        name: requests

    - name: Import the influx key into apt
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present

    - name: Add influx deb repository
      apt_repository:
        repo: 'deb https://repos.influxdata.com/debian buster stable'
        state: present
        update_cache: yes

    - name: Install InfluxDB
      apt:
        name: influxdb
        update_cache: yes
        cache_valid_time: 3600

    - name: install influxdb.conf
      copy:
        src: files/etc/influxdb/influxdb.conf
        dest: /etc/influxdb/influxdb.conf
        owner: root
        group: root
        mode: 0644

    - name: Create /data/influx directory
      file:
        path: /data/influxdb
        state: directory
        owner: influxdb
        group: influxdb
        mode: 0644

    - name: install influx-ramdisk.sh
      copy:
        src: files/usr/local/bin/influx-ramdisk.sh
        dest: /usr/local/bin/influx-ramdisk.sh
        owner: root
        group: root
        mode: 0755

    - name: Create influx systemd directory
      file:
        path: /etc/systemd/system/influxdb.service.d
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: install ramdisk.conf
      copy:
        src: files/etc/systemd/system/influxdb.service.d/ramdisk.conf
        dest: /etc/systemd/system/influxdb.service.d/ramdisk.conf
        owner: root
        group: root
        mode: 0644

    - name: Install Telegraf
      apt:
        name: telegraf
        update_cache: yes
        cache_valid_time: 3600

    - name: install telegraf.conf
      copy:
        src: files/etc/telegraf/telegraf.conf
        dest: /etc/telegraf/telegraf.conf
        owner: root
        group: root
        mode: 0644

    - name: Add telegraf user to dialout group
      user:
        name: telegraf
        groups: dialout
        append: yes

    - name: Install Chronograf
      apt:
        name: chronograf
        update_cache: yes
        cache_valid_time: 3600

    - name: Configure chronograf db
      lineinfile:
        dest: /lib/systemd/system/chronograf.service
        regexp: '^Environment="BOLT_PATH=/var/lib/chronograf/chronograf-v1.db"$'
        line: 'Environment="BOLT_PATH=/data/chronograf/chronograf-v1.db"'
        backrefs: yes

    - name: Create chronograf directory
      file:
        path: /data/chronograf
        state: directory
        owner: chronograf
        group: chronograf
        mode: 0644

    - name: Import the Mosquitto GPG key into apt
      apt_key:
        url: http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
        state: present

    - name: Add Mosquitto deb repository
      apt_repository:
        repo: 'deb http://repo.mosquitto.org/debian buster main'
        state: present

    - name: Install Mosquitto
      apt:
        name: mosquitto
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Mosquitto Clients
      apt:
        name: mosquitto-clients
        state: present
        update_cache: yes

    - name: install mosquitto.conf
      copy:
        src: files/etc/mosquitto/mosquitto.conf
        dest: /etc/mosquitto/mosquitto.conf
        owner: root
        group: root
        mode: 0644

    - name: enable mosquitto autostart with systemd
      systemd:
        name: mosquitto
        enabled: yes
        masked: no

    - name: install systemd service for heating-settings
      copy:
        src: files/etc/systemd/system/heating-settings.service
        dest: /etc/systemd/system/heating-settings.service
        owner: root
        group: root
        mode: 0755

    - name: enable heating-settings autostart with systemd
      systemd:
        name: heating-settings
        enabled: yes
        masked: no

    - name: Run the data sync script every minute
      cron:
        name: "sync data"
        job: "python /usr/local/tycoch/software/bin/sync-data.py /etc/datasync.json >> /var/log/datasync.log 2>>datasync.error.log"

    - name: Install lighttpd
      apt:
        name: lighttpd
        state: installed
        update_cache: yes

    - name: install lighttpd.conf
      copy:
        src: files/etc/lighttpd/lighttpd.conf
        dest: /etc/lighttpd/lighttpd.conf
        owner: root
        group: root
        mode: 0644

    - name: Add bjpirt user
      user:
        name: bjpirt
        groups: root,sudo,dialout
        append: yes
        generate_ssh_key: yes
        password: $6$tRtDhYwvnkL94Dg2$Gnpb69oM7XjtbUyuQ5hW48RBs2TOIwrZWXsUaxeIJ.xXlp86ecbSbmdmBWXQaINdz1Tt0cIVLHHHA/8.5oLTS/
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        shell: /bin/bash

    - name: Change password for pi user
      user:
        name: pi
        password: $6$tRtDhYwvnkL94Dg2$Gnpb69oM7XjtbUyuQ5hW48RBs2TOIwrZWXsUaxeIJ.xXlp86ecbSbmdmBWXQaINdz1Tt0cIVLHHHA/8.5oLTS/

    - name: Set authorized key for bjpirt
      authorized_key:
        user: bjpirt
        state: present
        key: "{{ lookup('file', 'files/id_rsa.bjpirt.pub') }}"

    - name: Download dotfiles
      become: yes
      become_user: bjpirt
      git:
        repo: 'https://github.com/bjpirt/dotfiles.git'
        dest: /home/bjpirt/dotfiles

    - name: Install dotfiles
      become: yes
      become_user: bjpirt
      shell: cd /home/bjpirt/dotfiles && ./install
