#!/usr/bin/env ansible-playbook
---
- hosts: tycoch
  sudo: yes
  gather_facts: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: safe
        update_cache: yes
        cache_valid_time: 3600
    - name: install update-ansible
      copy:
        src: files/usr/local/bin/update-ansible
        dest: /usr/local/bin/
        owner: root
        group: staff
        mode: 0755
    - name: Update repositories cache and install dnsmasq
      apt:
        name: dnsmasq
        update_cache: yes
        cache_valid_time: 3600
    - name: install dnsmasq.conf
      copy:
        src: files/etc/dnsmasq.conf
        dest: /etc/dnsmasq.conf
        owner: root
        group: staff
        mode: 0644
    - name: Update repositories cache and install hostapd
      apt:
        name: hostapd
        update_cache: yes
        cache_valid_time: 3600
    - name: install interfaces
      copy:
        src: files/etc/network/interfaces
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: 0644
    - name: install hosts
      copy:
        src: files/etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
    - name: install hostapd.conf
      copy:
        src: files/etc/hostapd/hostapd.conf
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: 0644
    - name: install uap0 startup script
      copy:
        src: files/etc/init.d/create-uap0
        dest: /etc/init.d/create-uap0
        owner: root
        group: root
        mode: 0755
    - name: enable uap0 startup script
      shell: update-rc.d create-uap0 defaults
    - name: Install git
      apt:
        name: git
        update_cache: yes
        cache_valid_time: 3600
    - name: Install vim
      apt:
        name: vim
        update_cache: yes
        cache_valid_time: 3600
    - name: Install tmux
      apt:
        name: tmux
        update_cache: yes
        cache_valid_time: 3600
    - name: Install pip
      apt:
        name: python-pip
        update_cache: yes
        cache_valid_time: 3600
    - name: Install the tycoch software
      git:
        repo: 'https://github.com/bjpirt/tycoch-software.git'
        dest: /usr/local/tycoch/software
        update: yes
    - name: Install pymodbus
      pip:
        name: pymodbus
    - name: Install InfluxDB
      apt:
        deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.3.6_armhf.deb
    - name: Install Telegraf
      apt:
        deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.4.2-1_armhf.deb
    - name: install telegraf.conf
      copy:
        src: files/etc/telegraf.conf
        dest: /etc/telegraf.conf
        owner: root
        group: root
        mode: 0644
    - name: Install Chronograf
      apt:
        deb: https://dl.influxdata.com/chronograf/releases/chronograf_1.3.9.0_armhf.deb
    - name: Import the Mosquitto GPG key into apt
      apt_key:
        url: http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
        state: present
    - name: Add Mosquitto deb repository
      apt_repository:
        repo: 'deb http://repo.mosquitto.org/debian stretch main'
        state: present
    - name: Install libssl
      apt:
        deb: http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
    - name: Install libwebsockets
      apt:
        deb: http://ftp.nz.debian.org/debian/pool/main/libw/libwebsockets/libwebsockets3_1.2.2-1_armhf.deb
    - name: Install Mosquitto
      apt:
        name: mosquitto
        state: installed
        update_cache: yes
    - name: Install Mosquitto Clients
      apt:
        name: mosquitto-clients
        state: installed
        update_cache: yes
    - name: install mosquitto.conf
      copy:
        src: files/etc/mosquitto/mosquitto.conf
        dest: /etc/mosquitto/mosquitto.conf
        owner: root
        group: root
        mode: 0644
