#!/usr/bin/env ansible-playbook
---
- hosts: tycoch
  become: yes
  gather_facts: yes
  vars:
    hostname: tycoch
    logger_ip: localhost
    eth0_ip: "192.168.0.10"
  roles:
    - base
    - static-ip-eth0
    - influxdb
    - chronograf
    - telegraf
    - mosquitto
    - tycoch
    - { role: readonly, when: not ignore_readonly | bool }
- hosts: homeserver
  become: yes
  gather_facts: yes
  vars:
    hostname: homeserver
  roles:
    - base
    - influxdb
    - chronograf
    - telegraf
    - mosquitto
    - { role: readonly, when: not ignore_readonly | bool }
