#!/usr/bin/env ansible-playbook
---
- hosts: tycoch_monitor
  become: yes
  gather_facts: yes
  vars:
    hostname: tycoch-monitor
  roles:
    - base
    - static-ip-eth0
    - telegraf
    - mosquitto
    - tycoch-monitor
    - rtc
    - readonly
- hosts: tycoch_logger
  become: yes
  gather_facts: yes
  vars:
    hostname: tycoch-logger
  roles:
    - base
    - static-ip-eth0
    - influxdb
    - chronograf
    - tycoch-logger
    - rtc
    - readonly
- hosts: tycoch_combined
  become: yes
  gather_facts: yes
  vars:
    hostname: tycoch
    logger_ip: localhost
  roles:
    - base
    - static-ip-eth0
    - influxdb
    - chronograf
    - telegraf
    - mosquitto
    - tycoch-monitor
    - tycoch-logger
    - readonly
- hosts: home_server
  become: yes
  gather_facts: yes
  vars:
    hostname: homeserver
  roles:
    - base
    - influxdb
    - chronograf
    - telegraf
    - mosquitto
    - readonly
