---
- name: Configure static IP on Ethernet
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface eth0
      static ip_address={{ eth0_ip }}/24
      static routers=192.168.0.1
      static domain_name_servers=192.168.0.1
