---
- name: Install Chronograf
  apt:
    name: chronograf
    update_cache: yes
    cache_valid_time: 3600

- name: Configure chronograf db
  lineinfile:
    dest: /lib/systemd/system/chronograf.service
    regexp: '^Environment="BOLT_PATH=/var/lib/chronograf/chronograf-v1.db"$'
    line: 'Environment="BOLT_PATH=/data/chronograf/chronograf-v1.db"'
    backrefs: yes

- name: Create chronograf systemd directory
  file:
    path: /etc/systemd/system/chronograf.service.d
    state: directory
    owner: root
    group: root
    mode: 0644

- name: install chronografdirs.conf
  copy:
    src: etc/systemd/system/chronograf.service.d/chronografdirs.conf
    dest: /etc/systemd/system/chronograf.service.d/chronografdirs.conf
    owner: root
    group: root
    mode: 0644

- name: install chronografdirs.sh
  copy:
    src: usr/local/bin/chronografdirs.sh
    dest: /usr/local/bin/chronografdirs.sh
    owner: root
    group: staff
    mode: 0755
