---
- name: Download ansible repo
  become: yes
  git:
    repo: https://github.com/bjpirt/raspberrypi-ansible-scripts.git
    dest: /opt/ansible/ansible-setup

- name: install update-ansible
  copy:
    src: usr/local/bin/update-ansible
    dest: /usr/local/bin/update-ansible
    owner: root
    group: root
    mode: 0755

- name: install mount-rw-root
  copy:
    src: usr/local/bin/mount-rw-root
    dest: /usr/local/bin/mount-rw-root
    owner: root
    group: root
    mode: 0755

- name: install update-chroot
  copy:
    src: usr/local/bin/update-chroot
    dest: /usr/local/bin/update-chroot
    owner: root
    group: root
    mode: 0755

- name: create mount directory
  ansible.builtin.file:
    path: /mnt/rw-root
    state: directory
    owner: root
    group: root
    mode: 0755
